export const products = [
  {
    _id: "1",
    name: "Wireless Bluetooth Earbuds",
    image: "/images/earbuds.jpg",
    description: "High-quality wireless earbuds with Bluetooth 5.0 technology.",
    brand: "SoundWave",
    category: "Electronics",
    price: 49.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: "2",
    name: "Smartwatch with Heart Rate Monitor",
    image: "/images/smartwatch.jpg",
    description:
      "A stylish smartwatch with a built-in heart rate monitor and fitness tracking features.",
    brand: "FitTech",
    category: "Electronics",
    price: 129.99,
    countInStock: 5,
    rating: 4.2,
    numReviews: 8,
  },
  {
    _id: "3",
    name: "Gaming Laptop",
    image: "/images/gaming-laptop.jpg",
    description:
      "Powerful gaming laptop with high-performance specifications for immersive gaming experiences.",
    brand: "TechMaster",
    category: "Computers",
    price: 1899.99,
    countInStock: 2,
    rating: 4.8,
    numReviews: 15,
  },

  {
    _id: "4",
    name: "Portable Bluetooth Speaker",
    image: "/images/bluetooth-speaker.jpg",
    description:
      "Compact and portable Bluetooth speaker with excellent sound quality.",
    brand: "AudioTech",
    category: "Electronics",
    price: 59.99,
    countInStock: 20,
    rating: 4.6,
    numReviews: 28,
  },
  {
    _id: "52",
    name: "Digital Camera with 4K Video",
    image: "/images/digital-camera.jpg",
    description:
      "High-resolution digital camera capable of shooting 4K videos and capturing stunning photos.",
    brand: "CapturePro",
    category: "Electronics",
    price: 699.99,
    countInStock: 0,
    rating: 4.9,
    numReviews: 10,
  },
  {
    _id: "5",
    name: "Smart Home Security System",
    image: "/images/security-system.jpg",
    description:
      "Complete smart home security system with motion sensors, cameras, and smartphone integration.",
    brand: "SafeGuard",
    category: "Home Security",
    price: 299.99,
    countInStock: 8,
    rating: 4.3,
    numReviews: 18,
  },
  {
    _id: "6",
    name: "Wireless Charging Pad",
    image: "/images/charging-pad.jpg",
    description:
      "Convenient wireless charging pad compatible with various smartphones and other Qi-enabled devices.",
    brand: "PowerUp",
    category: "Electronics",
    price: 29.99,
    countInStock: 15,
    rating: 4.0,
    numReviews: 6,
  },
  {
    _id: "7",
    name: "Ultra HD 4K Smart TV",
    image: "/images/smart-tv.jpg",
    description:
      "Immerse yourself in stunning visuals with this Ultra HD 4K Smart TV with built-in streaming apps.",
    brand: "VisualTech",
    category: "Electronics",
    price: 899.99,
    countInStock: 4,
    rating: 4.7,
    numReviews: 23,
  },
  {
    _id: "8",
    name: "Wireless Noise-Canceling Headphones",
    image: "/images/headphones.jpg",
    description:
      "Premium wireless headphones with active noise cancellation for an immersive listening experience.",
    brand: "AudioBliss",
    category: "Electronics",
    price: 199.99,
    countInStock: 6,
    rating: 4.5,
    numReviews: 14,
  },
  {
    _id: "9",
    name: "Professional DSLR Camera",
    image: "/images/dslr-camera.jpg",
    description:
      "A high-quality DSLR camera for professional photographers with advanced features and lens compatibility.",
    brand: "PixelPerfect",
    category: "Electronics",
    price: 1799.99,
    countInStock: 1,
    rating: 4.8,
    numReviews: 32,
  },
];
